// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhgbijoqqsprwyjuqbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZ2Jpam9xcXNwcnd5anVxYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTUwNjQsImV4cCI6MjA3NDM5MTA2NH0.jbl7nKelOMSMzkb_ekb79HojVq0su830IjsK2Fu-9Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});